version: "3"

services:

  database:
    container_name: psql
    image: postgres
    build:
      context: ./db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./volumes/postgres-data/postgres:/var/lib/postgresql/data006
    networks:
      - network001

  server:
    container_name: server
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - network001


networks:
  network001:

volumes:
  db:
